matrix:
  include:
    - language: rust
      rust:
        - nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
      fast_finish: true

    - language: python
      python:
        - "3.6"
      install:
        - pip install matplotlib