matrix:
  include:
    - language: rust
      rust:
        - nightly
      python:
        - "3.6"
      env:
        - PythonVersion=3.6
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
      fast_finish: true
