matrix:
  include:
    - language: rust
      rust:
        - nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
      fast_finish: true
      before_install:
        - sudo apt-get update
        - sudo apt-get install python3.5
        - pyenv global system 3.5
