matrix:
  include:
    - language: rust
      rust:
        - nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
      fast_finish: true
      before_install:
        - pyenv install 3.6.7
        - pyenv global system 3.6.7
