[package]
name = "peroxide"
version = "0.28.1"
authors = ["axect <axect@outlook.kr>"]
edition = "2018"
description = "Rust comprehensive scientific computation library contains linear algebra, numerical analysis, statistics and machine learning tools with farmiliar syntax"
repository = "https://github.com/Axect/Peroxide"
license = "MIT OR Apache-2.0"
categories = ["science"]
readme = "README.md"
documentation = "https://peroxide.surge.sh"
keywords = ["Numeric", "Science", "Dataframe", "Plot", "LinearAlgebra"]
exclude = ["example_data/", "src/bin/", "benches/", "example/", "test_data/", "peroxide-ad2"]

[badges]
travis-ci = { repository = "axect/peroxide" }
maintenance = { status = "actively-developed" }

[dev-dependencies]
float-cmp = "0.8"

[dependencies]
csv = "1.1"
rand = "0.7"
rand_distr = "0.3"
order-stat = "0.1"
puruspe = "0.1"
matrixmultiply = "0.2"
peroxide-ad = { version = "0.1" }
indexmap = { version = "1.6" }
netcdf = { version = "0.5", optional = true, default_features = false }
pyo3 = { version = "0.12", optional = true }
blas = { version = "0.20", optional = true }
lapack = { version = "0.16", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
json = { version = "0.12" }

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[features]
default = []
O3 = ["blas", "lapack"]
plot = ["pyo3"]
nc = ["netcdf"]
