[package]
name = "peroxide"
version = "0.1.1"
authors = ["axect <edeftg@gmail.com>"]
description = "Rust Numeric Library"
repository = "https://github.com/Axect/Peroxide"
license = "BSD-3-Clause"

[dependencies]