[package]
name = "peroxide"
version = "0.6.9"
authors = ["axect <edeftg@gmail.com>"]
description = "Rust numeric library contains linear algebra, numerical analysis, statistics and machine learning tools with R, MATLAB, Python like macros"
repository = "https://github.com/Axect/Peroxide"
license = "BSD-3-Clause"
categories = ["science"]
readme = "README.md"
documentation = "https://docs.rs/peroxide/"
keywords = ["Numeric", "R", "Scientific"]

[badges]
travis-ci = { repository = "Axect/Peroxide", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
csv = "1"
rand = "0.5"
