[package]
name = "peroxide"
version = "0.17.1"
authors = ["axect <edeftg@gmail.com>"]
description = "Rust comprehensive scientific computation library contains linear algebra, numerical analysis, statistics and machine learning tools with farmiliar syntax"
repository = "https://github.com/Axect/Peroxide"
license = "BSD-3-Clause"
categories = ["science"]
readme = "README.md"
documentation = "https://docs.rs/peroxide/"
keywords = ["Numeric", "R", "MATLAB", "Python", "Scientific"]
exclude = ["example_data/", "src/bin/", "benches/", "example/"]

[badges]
travis-ci = { repository = "axect/peroxide" }
maintenance = { status = "actively-developed" }

[dependencies]
csv = "1.1"
rand = "0.7"
special = "0.8"
indexmap = { version = "1.2", optional = true }
netcdf = { version = "0.1", optional = true }
pyo3 = { version = "0.8", optional = true }
blas = { version = "0.20", optional = true }
lapack = { version = "0.16", optional = true }
packed_simd = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[features]
default = []
oxidize = ["blas", "lapack", "packed_simd"]
plot = ["pyo3"]
dataframe = ["netcdf", "indexmap"]
