[package]
name = "peroxide"
version = "0.12.1"
authors = ["axect <edeftg@gmail.com>"]
description = "Rust numeric library contains linear algebra, numerical analysis, statistics and machine learning tools with R, MATLAB, Python like macros"
repository = "https://github.com/Axect/Peroxide"
license = "BSD-3-Clause"
categories = ["science"]
readme = "README.md"
documentation = "https://docs.rs/peroxide/"
keywords = ["Numeric", "R", "MATLAB", "Python", "Scientific"]
exclude = ["example_data/", "src/bin/"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
csv = "1"
rand = "0.7"
special = "0.8"
serde = "1"
serde-pickle = "0.5"
pyo3 = "0.7"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]
